export const allArticles = [
  {
    slug: "perfectionism-a-path-to-nowhere",
    title: "Perfectionism: A Path to Nowhere",
    publishedAt: "2024-06-17",
    updatedAt: "2024-06-18",
    summary: "Test summary",
    author: "Arman Ahmadi",
    keywords: ["test"],
    ogImage: "/articles/test.png",
    ogDescription: "Test description",
    ogTitle: "Test OG Title",
    ogUrl: "https://armancodes.com/articles/perfectionism-a-path-to-nowhere",
    twitterDescription: "Test description",
    twitterTitle: "Test Twitter Title",
    twitterImage: "/articles/test.png",
    shareLink: "/articles/perfectionism-a-path-to-nowhere",
    canonical: "",
    baseUrl: "https://armancodes.com/",
    body: { code: "<div>MDX</div>", raw: "MDX content" },
    isDraft: false,
    tags: ["Perfectionism"],
    hasSeries: false,
    hasSidebarLinks: false,
  },
];
