export const allArticles = [
  {
    slug: "perfectionism-a-path-to-nowhere",
    title: "Perfectionism: A Path to Nowhere",
    publishedAt: "2024-06-17",
    updatedAt: "2024-06-18",
    summary: "Test summary",
    author: "Arman Ahmadi",
    keywords: ["test"],
    ogImage: "/articles/test.png",
    ogDescription: "Test description",
    ogTitle: "Test OG Title",
    ogUrl: "https://armancodes.com/articles/perfectionism-a-path-to-nowhere",
    twitterDescription: "Test description",
    twitterTitle: "Test Twitter Title",
    twitterImage: "/articles/test.png",
    shareLink: "/articles/perfectionism-a-path-to-nowhere",
    canonical: "",
    baseUrl: "https://armancodes.com/",
    body: { code: "<div>MDX</div>", raw: "MDX content" },
    isDraft: false,
    tags: ["Perfectionism"],
    hasSeries: false,
    hasSidebarLinks: false,
    image: "/images/article.png",
    category: "Testing",
    metaDescription: "Test meta description",
    robots: "index,follow",
  },
  {
    slug: "php-vs-golang-developer-perspective",
    title:
      "PHP vs. GoLang: A Developer’s Perspective on Control, Simplicity, and Ecosystem Differences",
    publishedAt: "2024-11-02",
    updatedAt: "2024-11-02",
    summary: "Test summary",
    author: "Arman Ahmadi",
    keywords: ["test"],
    ogImage: "/articles/test.png",
    ogDescription: "Test description",
    ogTitle: "Test OG Title",
    ogUrl:
      "https://armancodes.com/articles/php-vs-golang-developer-perspective",
    twitterDescription: "Test description",
    twitterTitle: "Test Twitter Title",
    twitterImage: "/articles/test.png",
    shareLink: "/articles/php-vs-golang-developer-perspective",
    canonical: "",
    baseUrl: "https://armancodes.com/",
    body: { code: "<div>MDX</div>", raw: "MDX content" },
    isDraft: false,
    tags: ["PHP"],
    hasSeries: false,
    hasSidebarLinks: false,
  },
];
