services:
  nextapp-staging:
    container_name: armancodes-com-staging
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    networks:
      - nginx_apps_network

networks:
  nginx_apps_network:
    external: true
    name: nginx_apps_network
