name: Deploy Staging

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            if [ ! -d ${{ secrets.SERVER_APP_PATH }}/.git ]; then
                sudo git clone https://github.com/${{ github.repository }} ${{ secrets.SERVER_APP_PATH }}
            else
                cd ${{ secrets.SERVER_APP_PATH }}
                sudo git fetch origin staging
                sudo git checkout staging
                sudo git reset --hard origin/staging
            fi
            cd ${{ secrets.SERVER_APP_PATH }}
            sudo make stop-staging
            sudo make build-staging
            sudo make start-staging
